Add doo plugin to support lein doo
Without it the following error happens
```
lein doo node "test-server" once
'doo' is not a task. See 'lein help'.
```

After it errors for a different reason:
```
lein doo node "test-server" once
java.lang.Exception: :cljsbuild :builds needs to be either a vector or a map
 at leiningen.doo$correct_builds$fn__1090.invoke (doo.clj:55)
```