Always run dispatch-after-past-events-callbacks!
This is because this function is used to set up for example pinging and
also has side-effect (like removing the `::after-past-events-dummy-event`).
If not executed, the `::after-past-events-dummy-event` will remain in
registered events and will be tried to subscribed to, which will result
in error, as there is no such smart contract event.

```
INFO will subscribe:
{:contract
 :district.server.web3-events/after-past-events-dummy-contract,
 :event :district.server.web3-events/after-past-events-dummy-event,
 :from-block 21751031}
 in district.server.web3-events[:109] at Tue Feb 11 2025 10:39:09 GMT+0000 (Coordinated Universal Time)
/deploy/server/ethlance_server.js:10009
oops.core.report_error_dynamically=function(a,b){if(oops.state.was_error_reported_QMARK_())return null;oops.state.mark_error_reported_BANG_();var c=oops.config.get_error_reporting();if(cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(cljs$cst$3
49$throw,c))throw oops.state.prepare_error_from_call_site(a,oops.helpers.wrap_data_in_enveloper_if_possible(oops.config.use_envelope_QMARK_(),b));if(cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(cljs$cst$731$console,c)){c=console.error;b=oop
s.helpers.wrap_data_in_enveloper_if_possible(oops.config.use_envelope_QMARK_(),

            ^

Error: Oops, Unexpected object value (nil)
    at /deploy/server/ethlance_server.js:10355:237
    at cljs_web3_next.eth.subscribe_events.cljs$core$IFn$_invoke$arity$variadic (/deploy/server/ethlance_server.js:10356:4)
    at district.server.smart_contracts.subscribe_events (/deploy/server/ethlance_server.js:10537:185)
    at /deploy/server/ethlance_server.js:10765:482
    at /deploy/server/ethlance_server.js:10766:241
    at cljs.core.LazySeq.sval (/deploy/server/ethlance_server.js:1003:154)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/deploy/server/ethlance_server.js:1009:255)
    at cljs.core.seq (/deploy/server/ethlance_server.js:710:172)
    at /deploy/server/ethlance_server.js:10766:335
    at cljs.core.LazySeq.sval (/deploy/server/ethlance_server.js:1003:154)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/deploy/server/ethlance_server.js:1009:343)
    at cljs.core.seq (/deploy/server/ethlance_server.js:710:172)
    at cljs.core.Cons.cljs$core$INext$_next$arity$1 (/deploy/server/ethlance_server.js:981:335)
    at cljs.core.next (/deploy/server/ethlance_server.js:712:434)
    at cljs.core.dorun.cljs$core$IFn$_invoke$arity$1 (/deploy/server/ethlance_server.js:2034:429)
    at cljs.core.doall.cljs$core$IFn$_invoke$arity$1 (/deploy/server/ethlance_server.js:2036:404) {
  'cljs$core$IPrintWithWriter$': {},
  'cljs$core$IPrintWithWriter$_pr_writer$arity$3': [Function (anonymous)]
}

Node.js v20.18.3
```